# This is a generated file. Not intended for manual editing.
services:
  learnassist.api:
    build:
      context: "/home/kayhan/RiderProjects/learnassist-modularmonolith"
      dockerfile: "src/API/LearnAssist.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/LearnAssist.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "learnassistapi:dev"
    ports: []
    volumes:
    - "/home/kayhan/RiderProjects/learnassist-modularmonolith/src/API/LearnAssist.Api:/app:rw"
    - "/home/kayhan/RiderProjects/learnassist-modularmonolith:/src:rw"
    - "/home/kayhan/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
